test_that("db_get_<table> functions work", {
    base_dir <- here::here("")
    load(fs::path(base_dir, "tests/t_data.RData"))

    db_file <- fs::path(base_dir, "tests/MIMIC-III.db")
    if (RSQLite::dbCanConnect(RSQLite::SQLite(), db_file)) {
        con <- RSQLite::dbConnect(RSQLite::SQLite(), db_file)
    } else {
        stop(stringr::str_c("Database file: ", db_file, " not found.", sep = ""))
    }

    admissions <- db_get_admissions(con)
    callout <- db_get_callout(con)
    caregivers <- db_get_caregivers(con)
    chartevents <- db_get_chartevents(con)
    cptevents <- db_get_cptevents(con)
    datetimeevents <- db_get_datetimeevents(con)
    diagnoses_icd <- db_get_diagnoses_icd(con)
    drgcodes <- db_get_drgcodes(con)
    d_cpt <- db_get_d_cpt(con)
    d_icd_diagnoses <- db_get_d_icd_diagnoses(con)
    d_icd_procedures <- db_get_d_icd_procedures(con)
    d_items <- db_get_d_items(con)
    d_labitems <- db_get_d_labitems(con)
    icustays <- db_get_icustays(con)
    inputevents_cv <- db_get_inputevents_cv(con)
    inputevents_mv <- db_get_inputevents_mv(con)
    labevents <- db_get_labevents(con)
    microbiologyevents <- db_get_microbiologyevents(con)
    noteevents <- db_get_noteevents(con)
    outputevents <- db_get_outputevents(con)
    patients <- db_get_patients(con)
    prescriptions <- db_get_prescriptions(con)
    procedureevents_mv <- db_get_procedureevents_mv(con)
    procedures_icd <- db_get_procedures_icd(con)
    services <- db_get_services(con)
    transfers <- db_get_transfers(con)

    RSQLite::dbDisconnect(con)

    expect_equal(t_admissions, admissions)
    expect_equal(t_callout, callout)
    expect_equal(t_caregivers, caregivers)
    expect_equal(t_chartevents, chartevents)
    expect_equal(t_cptevents, cptevents)
    expect_equal(t_datetimeevents, datetimeevents)
    expect_equal(t_diagnoses_icd, diagnoses_icd)
    expect_equal(t_drgcodes, drgcodes)
    expect_equal(t_d_cpt, d_cpt)
    expect_equal(t_d_icd_diagnoses, d_icd_diagnoses)
    expect_equal(t_d_icd_procedures, d_icd_procedures)
    expect_equal(t_d_items, d_items)
    expect_equal(t_d_labitems, d_labitems)
    expect_equal(t_icustays, icustays)
    expect_equal(t_inputevents_cv, inputevents_cv)
    expect_equal(t_inputevents_mv, inputevents_mv)
    expect_equal(t_labevents, labevents)
    expect_equal(t_microbiologyevents, microbiologyevents)
    expect_equal(t_noteevents, noteevents)
    expect_equal(t_outputevents, outputevents)
    expect_equal(t_patients, patients)
    expect_equal(t_prescriptions, prescriptions)
    expect_equal(t_procedureevents_mv, procedureevents_mv)
    expect_equal(t_procedures_icd, procedures_icd)
    expect_equal(t_services, services)
    expect_equal(t_transfers, transfers)
})
