test_that("db_get_<table> functions work", {
    db_file <- system.file("extdata", "MIMIC-III.db", package = "MIMIC3db")
    if (RSQLite::dbCanConnect(RSQLite::SQLite(), db_file)) {
        con <- RSQLite::dbConnect(RSQLite::SQLite(), db_file)
    } else {
        stop(stringr::str_c("Database file: ", db_file, " not found.", sep = ""))
    }

    expect_equal(t_admissions, db_get_admissions(con))
    expect_equal(t_callout, db_get_callout(con))
    expect_equal(t_caregivers, db_get_caregivers(con))
    expect_equal(t_chartevents, db_get_chartevents(con))
    expect_equal(t_cptevents, db_get_cptevents(con))
    expect_equal(t_datetimeevents, db_get_datetimeevents(con))
    expect_equal(t_diagnoses_icd, db_get_diagnoses_icd(con))
    expect_equal(t_drgcodes, db_get_drgcodes(con))
    expect_equal(t_d_cpt, db_get_d_cpt(con))
    expect_equal(t_d_icd_diagnoses, db_get_d_icd_diagnoses(con))
    expect_equal(t_d_icd_procedures, db_get_d_icd_procedures(con))
    expect_equal(t_d_items, db_get_d_items(con))
    expect_equal(t_d_labitems, db_get_d_labitems(con))
    expect_equal(t_icustays, db_get_icustays(con))
    expect_equal(t_inputevents_cv, db_get_inputevents_cv(con))
    expect_equal(t_inputevents_mv, db_get_inputevents_mv(con))
    expect_equal(t_labevents, db_get_labevents(con))
    expect_equal(t_microbiologyevents, db_get_microbiologyevents(con))
    expect_equal(t_noteevents, db_get_noteevents(con))
    expect_equal(t_outputevents, db_get_outputevents(con))
    expect_equal(t_patients, db_get_patients(con))
    expect_equal(t_prescriptions, db_get_prescriptions(con))
    expect_equal(t_procedureevents_mv, db_get_procedureevents_mv(con))
    expect_equal(t_procedures_icd, db_get_procedures_icd(con))
    expect_equal(t_services, db_get_services(con))
    expect_equal(t_transfers, db_get_transfers(con))

    RSQLite::dbDisconnect(con)
})
